default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  url: <%= ENV["DATABASE_URL"] %>
  port: <%= ENV["DATABASE_PORT"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: cigrp_dev

test:
  <<: *default
  database: cigrp_test

production:
  <<: *default
  database: cigrp
